### ISSUE TITLE
Symbols for buttons not appearing

### ISSUE THREAD

**Issue by BeanTeen** [the-expanse/SideQuest#461] opened 2020-03-28 23:39 UTC
Whenever I open the desktop app all the icons on the top have the basic code showing assigned to there actions instead of the symbols. The back and forwards arrows aren’t actual arrows they’re just text that says “arrow_forward” and “arrow_backward”. Can you please make a fix for this?
![50270D8C-C988-4AA3-A960-79941C649384](https://user-images.githubusercontent.com/62818665/77836337-c6bc8f00-712b-11ea-84cd-2d62866142a8.jpeg)

**Comment by shaneharris** [comment] 2020-03-29 00:31
Hi there, these are leaded remotely from google icon font available at -https://fonts.googleapis.com/icon?family=Material+Icons 

What you are seeing is what happens when these do not load for some reason ( open the above url to see if it loads for you ) and this is usually caused by an SSL issue and/or a VPN/web filter on your PC. As this is out of scope of sidequest ill close this. 

Thanks!

**Closed by shaneharris** 2020-03-29 00:31 UTC
