### ISSUE TITLE
Clean up failed install attempts

### ISSUE THREAD

**Issue by korenmic** [the-expanse/SideQuest#538] opened 2020-05-17 12:04 UTC
I have noticed that sometimes when I have free space `X`
and I attempt to install something, during the installation attempt I now have free space `X-Y` (less)
the installation attempt will sometimes fail.
Expected behavior would be that the free space would go back to being `X`
Actual behavior is that it is still `X-Y`.

I don't know if this is a quest issue, adb issue, android issue, or sidequest issude
but it has to be fixed, as without fixing all that lost free space will remain lost forever for no good reason.

This happened to me while attempting to install `syon-bolt-quest-pre-release`

**Comment by sidequestlegend** [comment] 2020-05-18 08:10
We will look into this and see if there is a workaround, thanks!

**Comment by sidequestlegend** [comment] 2020-05-27 13:11
I cannot reproduce this one and it seems from #537 it might actually be caused by something else. Closing for now but i can reopen if this requires further investigation.

**Closed by sidequestlegend** 2020-05-27 13:11 UTC
Labels: desktop app
