### ISSUE TITLE
Update seems to cause SQ to hang

### ISSUE THREAD

**Issue by alexarnoldy** [the-expanse/SideQuest#334] opened 2019-12-16 18:05 UTC
Updating from 0.7.2 to 0.8.2 caused SQ to hang when starting the app.

Removing app and installing fresh 0.8.2 seems to resolve.

Equip: Middle of the road Dell Inspirion 15 with Win10, fully up to date on patches.

**Comment by shaneharris** [comment] 2019-12-26 17:05
i had heard reports of this and never found the cause. The people who reported it though also confirmed that the update to 0.8.3 fixed it. Im going to close this for now but ill keep an eye out for this. thank you

**Closed by shaneharris** 2019-12-26 17:05 UTC
