### ISSUE TITLE
Segmentation error

### ISSUE THREAD

**Issue by wirwolf** [the-expanse/SideQuest#235] opened 2019-07-08 07:28 UTC
Error
```
root@Developer-PC:~/SideQuest-0.4.2$ ./sidequest 
Ошибка сегментирования (стек памяти сброшен на диск)

```

My system info
```
root@Developer-PC:~# cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.2 LTS"
root@Developer-PC:~# 
```

pkg: https://pastebin.com/UpQgZiDm

**Comment by shaneharris** [comment] 2019-07-14 10:25
I cant reproduce this error, did you have any success since reporting this?

**Comment by wirwolf** [comment] 2019-07-15 12:25
Nope(
What information can I present to you?

**Comment by shaneharris** [comment] 2019-08-07 19:41
Hi there! Sorry for the late reply, this one got away from me somehow. I cant see any reason why you would get that error but can i ask you to try the latest version? We have just dropped 2 native dependencies and this could have been caused by one of them

**Comment by shaneharris** [comment] 2019-08-15 15:08
closing as dead

**Closed by shaneharris** 2019-08-15 15:08 UTC

**Comment by wirwolf** [comment] 2020-08-11 18:49
@sidequestlegend 
```
wir_wolf@DEVELOPER-PC:~/Oculus/SideQuest-0.10.11$ gdb ./sidequest 
GNU gdb (Ubuntu 9.1-0ubuntu1) 9.1
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
--Type <RET> for more, q to quit, c to continue without paging--
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
BFD: warning: /home/wir_wolf/Oculus/SideQuest-0.10.11/sidequest has a corrupt string table index - ignoring
Reading symbols from ./sidequest...
(No debugging symbols found in ./sidequest)
(gdb) run
Starting program: /home/wir_wolf/Oculus/SideQuest-0.10.11/sidequest 

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7fdca80 in ?? () from /lib64/ld-linux-x86-64.so.2
(gdb) 


```
