### ISSUE TITLE
Sync selected not patching songs

### ISSUE THREAD

**Issue by Maxynola** [the-expanse/SideQuest#50] opened 2019-06-03 23:44 UTC
System.IO.InvalidDataException: End of Central Directory record could not be found. at System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory() at System.IO.Compression.ZipArchive.Init(Stream stream, ZipArchiveMode mode, Boolean leaveOpen) at System.IO.Compression.ZipArchive..ctor(Stream stream, ZipArchiveMode mode, Boolean leaveOpen, Encoding entryNameEncoding) at System.IO.Compression.ZipFile.Open(String archiveFileName, ZipArchiveMode mode, Encoding entryNameEncoding) at jsonApp.Program.RunInvocation(Invocation inv) in C:\projects\QuestSaberPatch\jsonApp\Program.cs:line 60

**Comment by ATechAdventurer** [comment] 2019-06-03 23:52
Duplicate of #49

**Closed by ATechAdventurer** 2019-06-03 23:52 UTC
Labels: duplicate
