### ISSUE TITLE
Custom maps are not recognized

### ISSUE THREAD

**Issue by Fatalution** [the-expanse/SideQuest#102] opened 2019-06-10 11:12 UTC
I have all of my custom maps dragged into the custom maps. I have used one oft he oldest Beat Saber patches for Quest and I have had all my songs working. I have basically dragged all the contents of ToConvert folder to the new location provided by SideQuest: AppData\Roaming\SideQuest\bsaber folder. However, the software spits out this error:

> Error, song has no info.dat: AppData\Roaming\SideQuest\bsaber\When Can I See You Again\autosaves, Error:null

Ok, tried to erase every autosave folder... Lo' and behold...

> Error, song is empty: C:\Users\vanya\AppData\Roaming\SideQuest\bsaber\When Can I See You Again

What? I have never had any issues before and the moment I'm trying to syc my custom maps using SideQuest, it fails for no apparent reason.

**Comment by Fatalution** [comment] 2019-06-10 11:18
[https://imgur.com/a/p8xvYOa](url)

**Comment by shaneharris** [comment] 2019-06-10 11:45
You have the wrong folder structure. It should be 

bsaber > somefoldername > songname > info.dat

for each song. Closing as working as intended

**Closed by shaneharris** 2019-06-10 11:45 UTC
