### ISSUE TITLE
SideQuest update and BeatSabre update create incompatibility..

### ISSUE THREAD

**Issue by robcooper2001** [the-expanse/SideQuest#271] opened 2019-07-27 14:00 UTC
Shane,
Aha! Turns out Beat Sabre had an update? I got new content anyway. And Sidequest did an update and then wouldn't work. Also, installing BeatOn made Beat Sabre tell me there was an update!! But it wouldn't update. Now it says SideQuest is not compatible with my current version. I uninstalled and reinstalled several times and SideQuest!!
Is there a SideQuest update for BeatSabre?

**Comment by Fauchschabe** [comment] 2019-07-27 16:04
@robcooper2001 ran in the same problem, can't patch nor restore my backup due to version incompatibility with Beat Saber 1.2.0.

**Comment by lifet8kr** [comment] 2019-07-27 16:40
I think  it has to do with the Oculus Update.

**Comment by srvrguy** [comment] 2019-07-27 16:59
Looks like a duplicate of #269. You can see the replies in there.

**Comment by Fauchschabe** [comment] 2019-07-27 16:59
After uninstalling the unpatched Beat Saber 1.2.0 I was able to install my patched backup manually using adb. Now everything runs fine, i can play my custom songs and even can patch again. Therefore I don't think the problem is related to the Oculus update.

**Closed by srvrguy** 2019-07-27 16:59 UTC
Labels: duplicate
