### ISSUE TITLE
Beast Saber Playlist support

### ISSUE THREAD

**Issue by TheYadda** [the-expanse/SideQuest#109] opened 2019-06-10 20:26 UTC
Currently you can make your own playlists, but you cannot import the ones that already exist on Beast Saber for download.

**Comment by drewbaumann** [comment] 2019-06-11 21:48
Cool idea.

**Comment by drewbaumann** [comment] 2019-06-12 18:26
Closing. Dupe of #77

**Closed by drewbaumann** 2019-06-12 18:26 UTC
